// types

export type FlagDetails = {
	fullName: string;
	name: string;
	keywords: string[];
}

// flag list
export const flagList = (): FlagDetails[] => {
	return [
		{ fullName: "Afghanistan", 						name: "af", keywords: ["004", "afg"] },
		{ fullName: "Aland Islands",					name: "ax", keywords: ["248", "ala"] },
		{ fullName: "Albania", 							name: "al", keywords: ["008", "alb"] },
		{ fullName: "Algeria", 							name: "dz", keywords: ["012", "dza"] },
		{ fullName: "American Samoa", 					name: "as", keywords: ["016", "asm"] },
		{ fullName: "Andorra", 							name: "ad", keywords: ["020", "and"] },
		{ fullName: "Angola", 							name: "ao", keywords: ["024", "ago"] },
		{ fullName: "Anguilla", 						name: "ai", keywords: ["660", "aia"] },
		{ fullName: "Antarctica", 						name: "aq", keywords: ["010", "ata"] },
		{ fullName: "Antigua and Barbuda", 				name: "ag", keywords: ["028", "atg"] },
		{ fullName: "Argentina", 						name: "ar", keywords: ["032", "arg"] },
		{ fullName: "Armenia", 							name: "am", keywords: ["051", "arm"] },
		{ fullName: "Aruba", 							name: "aw", keywords: ["533", "abw"] },
		{ fullName: "Australia", 						name: "au", keywords: ["036", "aus"] },
		{ fullName: "Austria", 							name: "at", keywords: ["040", "aut"] },
		{ fullName: "Azerbaijan", 						name: "az", keywords: ["031", "aze"] },
		{ fullName: "Bahamas", 							name: "bs", keywords: ["044", "bhs"] },
		{ fullName: "Bahrain", 							name: "bh", keywords: ["048", "bhr"] },
		{ fullName: "Bangladesh", 						name: "bd", keywords: ["050", "bgd"] },
		{ fullName: "Barbados", 						name: "bb", keywords: ["052", "brb"] },
		{ fullName: "Belarus", 							name: "by", keywords: ["112", "blr"] },
		{ fullName: "Belgium", 							name: "be", keywords: ["056", "bel"] },
		{ fullName: "Belize", 							name: "bz", keywords: ["084", "blz"] },
		{ fullName: "Benin", 							name: "bj", keywords: ["204", "ben"] },
		{ fullName: "Bermuda", 							name: "bm", keywords: ["060", "bmu"] },
		{ fullName: "Bhutan", 							name: "bt", keywords: ["064", "btn"] },
		{ fullName: "Bolivia", 							name: "bo", keywords: ["068", "bol"] },
		{ fullName: "Bonaire, Sint Eustatius and Saba",	name: "bq", keywords: ["535", "bes"] },
		{ fullName: "Bosnia and Herzegovina",			name: "ba", keywords: ["070", "bih"] },
		{ fullName: "Botswana", 						name: "bw", keywords: ["072", "bwa"] },
		{ fullName: "Bouvet Island",					name: "bv", keywords: ["074", "bvt"] },
		{ fullName: "Brazil", 							name: "br", keywords: ["076", "bra"] },
		{ fullName: "British Indian Ocean Territory", 	name: "io", keywords: ["086", "iot"] },
		{ fullName: "Brunei Darussalam", 				name: "bn", keywords: ["096", "brn"] },
		{ fullName: "Bulgaria", 						name: "bg", keywords: ["100", "bgr"] },
		{ fullName: "Burkina Faso", 					name: "bf", keywords: ["854", "bfa"] },
		{ fullName: "Burundi", 							name: "bi", keywords: ["108", "bdi"] },
		{ fullName: "Cabo Verde", 						name: "cv", keywords: ["132", "cpv"] },
		{ fullName: "Cambodia", 						name: "kh", keywords: ["116", "khm"] },
		{ fullName: "Cameroon", 						name: "cm", keywords: ["120", "cmr"] },
		{ fullName: "Canada", 							name: "ca", keywords: ["124", "can"] },
		{ fullName: "Chad", 							name: "td", keywords: ["148", "tcd"] },
		{ fullName: "Chile", 							name: "cl", keywords: ["152", "chl"] },
		{ fullName: "China", 							name: "cn", keywords: ["156", "chn"] },
		{ fullName: "Colombia", 						name: "co", keywords: ["170", "col"] },
		{ fullName: "Croatia", 							name: "hr", keywords: ["191", "hrv"] },
		{ fullName: "Cyprus", 							name: "cy", keywords: ["196", "cyp"] },
		{ fullName: "Czech Republic", 					name: "cz", keywords: ["203", "cze"] },
		{ fullName: "Denmark", 							name: "dk", keywords: ["208", "dnk"] },
		{ fullName: "Dominican Republic", 				name: "do", keywords: ["214", "dom"] },
		{ fullName: "Ecuador", 							name: "ec", keywords: ["218", "ecu"] },
		{ fullName: "Egypt", 							name: "eg", keywords: ["818", "egy"] },
		{ fullName: "El Salvador", 						name: "sv", keywords: ["222", "slv"] },
		{ fullName: "Equatorial Guinea", 				name: "gq", keywords: ["226", "gnq"] },
		{ fullName: "Eritrea", 							name: "er", keywords: ["232", "eri"] },
		{ fullName: "Estonia", 							name: "ee", keywords: ["233", "est"] },
		{ fullName: "Eswatini", 						name: "sz", keywords: ["748", "swz"] },
		{ fullName: "Ethiopia", 						name: "et", keywords: ["231", "eth"] },
		{ fullName: "Finland", 							name: "fi", keywords: ["246", "fin"] },
		{ fullName: "France", 							name: "fr", keywords: ["250", "fra"] },
		{ fullName: "Germany", 							name: "de", keywords: ["276", "deu"] },
		{ fullName: "Great Britain", 					name: "gb", keywords: ["826", "gbr"] },
		{ fullName: "Greece", 							name: "gr", keywords: ["300", "grc"] },
		{ fullName: "Guatemala",						name: "gt", keywords: ["320", "gtm"] },
		{ fullName: "Guinea-Bissau", 					name: "gw", keywords: ["624", "gnb"] },
		{ fullName: "Guinea", 							name: "gn", keywords: ["324", "gin"] },
		{ fullName: "Guyana", 							name: "gy", keywords: ["328", "guy"] },
		{ fullName: "Haiti", 							name: "ht", keywords: ["332", "hti"] },
		{ fullName: "Honduras", 						name: "hn", keywords: ["340", "hnd"] },
		{ fullName: "Hong Kong", 						name: "hk", keywords: ["344", "hkg"] },
		{ fullName: "Hungary", 							name: "hu", keywords: ["348", "hun"] },
		{ fullName: "Indonesia", 						name: "id", keywords: ["360", "idn"] },
		{ fullName: "Ireland", 							name: "ie", keywords: ["372", "irl"] },
		{ fullName: "Israel", 							name: "il", keywords: ["376", "isr"] },
		{ fullName: "Italy", 							name: "it", keywords: ["380", "ita"] },
		{ fullName: "Ivory Coast", 						name: "ci", keywords: ["384", "civ"] },
		{ fullName: "Japan", 							name: "jp", keywords: ["392", "jpn"] },
		{ fullName: "Japan", 							name: "jp", keywords: ["392", "jpn"] },
		{ fullName: "Luxembourg", 						name: "lu", keywords: ["442", "lux"] },
		{ fullName: "Macao", 							name: "mo", keywords: ["446", "mac"] },
		{ fullName: "Malawi", 							name: "mw", keywords: ["454", "mwi"] },
		{ fullName: "Malaysia", 						name: "my", keywords: ["458", "mys"] },
		{ fullName: "Maldives", 						name: "mv", keywords: ["462", "mdv"] },
		{ fullName: "Mali", 							name: "ml", keywords: ["466", "mli"] },
		{ fullName: "Malta", 							name: "mt", keywords: ["470", "mlt"] },
		{ fullName: "Marshall Islands", 				name: "mh", keywords: ["584", "mhl"] },
		{ fullName: "Mauritania", 						name: "mr", keywords: ["478", "mrt"] },
		{ fullName: "Mauritius", 						name: "mu", keywords: ["480", "mus"] },
		{ fullName: "Mexico", 							name: "mx", keywords: ["484", "mex"] },
		{ fullName: "Micronesia", 						name: "fm", keywords: ["583", "fsm"] },
		{ fullName: "Moldova", 							name: "md", keywords: ["498", "mda"] },
		{ fullName: "Monaco", 							name: "mc", keywords: ["492", "mco"] },
		{ fullName: "Mongolia", 						name: "mn", keywords: ["496", "mng"] },
		{ fullName: "Montenegro", 						name: "me", keywords: ["499", "mne"] },
		{ fullName: "Morocco", 							name: "ma", keywords: ["504", "mar"] },
		{ fullName: "Mozambique", 						name: "mz", keywords: ["508", "moz"] },
		{ fullName: "Myanmar", 							name: "mm", keywords: ["104", "mya"] },
		{ fullName: "Namibia", 							name: "na", keywords: ["516", "nam"] },
		{ fullName: "Nauru", 							name: "nr", keywords: ["520", "nru"] },
		{ fullName: "Nepal", 							name: "np", keywords: ["524", "npl"] },
		{ fullName: "Netherlands", 						name: "nl", keywords: ["528", "nld"] },
		{ fullName: "New Zealand", 						name: "nz", keywords: ["554", "nzl"] },
		{ fullName: "Nicaragua", 						name: "ni", keywords: ["558", "nic"] },
		{ fullName: "Niger", 							name: "ne", keywords: ["562", "ner"] },
		{ fullName: "Nigeria", 							name: "ng", keywords: ["566", "nga"] },
		{ fullName: "North Macedonia", 					name: "mk", keywords: ["807", "mkd"] },
		{ fullName: "Norway", 							name: "no", keywords: ["578", "nor"] },
		{ fullName: "Oman", 							name: "om", keywords: ["512", "omn"] },
		{ fullName: "Pakistan", 						name: "pk", keywords: ["586", "pak"] },
		{ fullName: "Palau", 							name: "pw", keywords: ["585", "plw"] },
		{ fullName: "Palestine", 						name: "ps", keywords: ["275", "pse"] },
		{ fullName: "Panama", 							name: "pa", keywords: ["591", "pan"] },
		{ fullName: "Papua New Guinea", 				name: "pg", keywords: ["598", "png"] },
		{ fullName: "Paraguay", 						name: "py", keywords: ["600", "pry"] },
		{ fullName: "Peru", 							name: "pe", keywords: ["604", "per"] },
		{ fullName: "Philippines", 						name: "ph", keywords: ["608", "phl"] },
		{ fullName: "Poland", 							name: "pl", keywords: ["616", "pol"] },
		{ fullName: "Portugal", 						name: "pt", keywords: ["620", "prt"] },
		{ fullName: "Portugal", 						name: "pt", keywords: ["620", "prt"] },
		{ fullName: "Puerto Rico", 						name: "pr", keywords: ["630", "pri"] },
		{ fullName: "Qatar", 							name: "qa", keywords: ["634", "qat"] },
		{ fullName: "Qatar", 							name: "qa", keywords: ["634", "qat"] },
		{ fullName: "Romania", 							name: "ro", keywords: ["642", "rou"] },
		{ fullName: "Russia", 							name: "ru", keywords: ["643", "rus"] },
		{ fullName: "Rwanda", 							name: "rw", keywords: ["646", "rwa"] },
		{ fullName: "Saint Kitts and Nevis", 			name: "kn", keywords: ["659", "kna"] },
		{ fullName: "Saint Lucia", 						name: "lc", keywords: ["662", "lca"] },
		{ fullName: "Saint Vincent and the Grenadines",	name: "vc", keywords: ["670", "vct"] },
		{ fullName: "Samoa", 							name: "ws", keywords: ["882", "wsm"] },
		{ fullName: "San Marino", 						name: "sm", keywords: ["674", "smr"] },
		{ fullName: "Sao Tome and Principe", 			name: "st", keywords: ["678", "stp"] },
		{ fullName: "Saudi Arabia", 					name: "sa", keywords: ["682", "sau"] },
		{ fullName: "Senegal", 							name: "sn", keywords: ["686", "sen"] },
		{ fullName: "Serbia", 							name: "rs", keywords: ["688", "srb"] },
		{ fullName: "Seychelles", 						name: "sc", keywords: ["690", "syc"] },
		{ fullName: "Sierra Leone", 					name: "sl", keywords: ["694", "sle"] },
		{ fullName: "Singapore", 						name: "sg", keywords: ["702", "sgp"] },
		{ fullName: "Slovenia", 						name: "si", keywords: ["705", "svn"] },
		{ fullName: "Solomon Islands", 					name: "sb", keywords: ["090", "slb"] },
		{ fullName: "Somalia", 							name: "so", keywords: ["706", "som"] },
		{ fullName: "South Africa", 					name: "za", keywords: ["710", "zaf"] },
		{ fullName: "South Korea", 						name: "kr", keywords: ["410", "kor"] },
		{ fullName: "South Sudan", 						name: "ss", keywords: ["728", "ssd"] },
		{ fullName: "Spain", 							name: "es", keywords: ["724", "esp"] },
		{ fullName: "Sri Lanka", 						name: "lk", keywords: ["144", "lka"] },
		{ fullName: "Sudan", 							name: "sd", keywords: ["729", "sdn"] },
		{ fullName: "Suriname", 						name: "sr", keywords: ["740", "sur"] },
		{ fullName: "Sweden", 							name: "se", keywords: ["752", "swe"] },
		{ fullName: "Switzerland", 						name: "ch", keywords: ["756", "che"] },
		{ fullName: "Syria", 							name: "sy", keywords: ["760", "syr"] },
		{ fullName: "Taiwan", 							name: "tw", keywords: ["158", "twn"] },
		{ fullName: "Tajikistan", 						name: "tj", keywords: ["762", "tjk"] },
		{ fullName: "Tanzania", 						name: "tz", keywords: ["834", "tza"] },
		{ fullName: "Thailand", 						name: "th", keywords: ["764", "tha"] },
		{ fullName: "Timor-Leste",  					name: "tl", keywords: ["626", "tls", "East Timor"] },
		{ fullName: "Togo", 							name: "tg", keywords: ["768", "tgo"] },
		{ fullName: "Tonga", 							name: "to", keywords: ["776", "ton"] },
		{ fullName: "Trinidad and Tobago", 				name: "tt", keywords: ["780", "tto"] },
		{ fullName: "Tunisia", 							name: "tn", keywords: ["788", "tun"] },
		{ fullName: "Turkey", 							name: "tr", keywords: ["792", "tur"] },
		{ fullName: "Turkey", 							name: "tr", keywords: ["792", "tur"] },
		{ fullName: "Turkmenistan", 					name: "tm", keywords: ["795", "tkm"] },
		{ fullName: "Tuvalu", 							name: "tv", keywords: ["798", "tuv"] },
		{ fullName: "Uganda", 							name: "ug", keywords: ["800", "uga"] },
		{ fullName: "Ukraine", 							name: "ua", keywords: ["804", "ukr"] },
		{ fullName: "Ukraine", 							name: "ua", keywords: ["804", "ukr"] },
		{ fullName: "United Arab Emirates", 			name: "ae", keywords: ["784", "are"] },
		{ fullName: "United Kingdom", 					name: "gb", keywords: ["826", "gbr"] },
		{ fullName: "United States", 					name: "us", keywords: ["840", "usa"] },
		{ fullName: "Uruguay", 							name: "uy", keywords: ["858", "ury"] },
		{ fullName: "Uzbekistan", 						name: "uz", keywords: ["860", "uzb"] },
		{ fullName: "Vanuatu", 							name: "vu", keywords: ["548", "vut"] },
		{ fullName: "Vatican City", 					name: "va", keywords: ["336", "vat"] },
		{ fullName: "Venezuela", 						name: "ve", keywords: ["862", "ven"] },
		{ fullName: "Vietnam", 							name: "vn", keywords: ["704", "vnm"] },
		{ fullName: "Yemen", 							name: "ye", keywords: ["887", "yem"] },
		{ fullName: "Zambia", 							name: "zm", keywords: ["894", "zmb"] },
		{ fullName: "Zimbabwe", 						name: "zw", keywords: ["716", "zwe"] },
		{ fullName: "Pirate Flag", 						name: "pirate", keywords: [] },
	];
}