export const dotsBounce = /*html*/`
	<svg
		version="1.1"
		xmlns="http://www.w3.org/2000/svg"
		viewBox="0 0 24 24"
		preserveAspectRatio="xMidYMid meet"
		x="0"
		y="0"
	>
		<circle
			cx="4"
			cy="12"
			r="3"
			fill="currentColor"
		>
			<animate
				attributeName="cy"
				begin="0"
				calcMode="spline"
				dur="1s"
				keySplines=".33,.66,.66,1;.33,0,.66,.33"
				values="12;6;12"
				repeatCount="indefinite"
			/>
		</circle>
		<circle
			cx="12"
			cy="12"
			r="3"
			fill="currentColor"
		>
			<animate
				attributeName="cy"
				begin="0.15s"
				calcMode="spline"
				dur="1s"
				keySplines=".33,.66,.66,1;.33,0,.66,.33"
				values="12;6;12"
				repeatCount="indefinite"
			/>
		</circle>
		<circle
			cx="20"
			cy="12"
			r="3"
			fill="currentColor"
		>
			<animate
				attributeName="cy"
				begin="0.3s"
				calcMode="spline"
				dur="1s"
				keySplines=".33,.66,.66,1;.33,0,.66,.33"
				values="12;6;12"
				repeatCount="indefinite"
			/>
		</circle>
	</svg>
`;
